### Health Check
GET http://localhost:3000/api/v1/health_check
Accept: application/json
Accept-Language: pt-BR

### Create company and first user
POST http://localhost:3000/api/v1/companies
Accept: application/json
Accept-Language: pt-BR
Content-Type: application/json

{
  "corporate_name": "Cauê e Kamilly Pães e Doces ME",
  "fantasy_name": "Cauê e Kamilly Pães e Doces ME",
  "email": "pesquisa@caueekamillypaesedocesme.com.br",
  "email_confirmation": "pesquisa@caueekamillypaesedocesme.com.br",
  "domain": "caueekamillypaesedocesme",
  "cnpj": "61992766000194",
  "users_attributes": [
    {
      "full_name": "Márcia Helena Duarte",
      "email": "marcia_duarte@hp.com",
      "email_confirmation": "marcia_duarte@hp.com",
      "cpf": "00717879925",
      "password": "R(dCe4w24o;t",
      "password_confirmation": "R(dCe4w24o;t"
    }
  ]
}

### Get company
GET http://localhost:3000/api/v1/companies/1
Accept: application/json
Accept-Language: pt-BR

### Get company by token
GET http://localhost:3000/api/v1/companies
Accept: application/json
Accept-Language: pt-BR
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJici5jb20uc2FudG9zLmV2YW5kcm8ubWFya2V0IiwiZXhwIjoxNjg3NTgyNDQ1LCJzdWIiOnsiY29tcGFueV9pZCI6MX19.H47V3kTUztWdw-wWQM4L36aGr3wHtC3BtpwaWgTc-ZA