### Health Check
GET http://localhost:3000/api/v1/health_check
Accept: application/json
Accept-Language: pt-BR

### Create company
POST http://localhost:3000/api/v1/companies
Accept: application/json
Accept-Language: pt-BR
Content-Type: application/json

{
  "corporate_name": "Cauê e Kamilly Pães e Doces ME",
  "fantasy_name": "Cauê e Kamilly Pães e Doces ME",
  "email": "pesquisa@caueekamillypaesedocesme.com.br",
  "email_confirmation": "pesquisa@caueekamillypaesedocesme.com.br",
  "domain": "caueekamillypaesedocesme",
  "cnpj": "61992766000194"
}

### Get company
GET http://localhost:3000/api/v1/companies/1
Accept: application/json
Accept-Language: pt-BR

### Get company by token
GET http://localhost:3000/api/v1/companies
Accept: application/json
Accept-Language: pt-BR
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJici5jb20uc2FudG9zLmV2YW5kcm8ubWFya2V0IiwiZXhwIjoxNjg3NTgyNDQ1LCJzdWIiOnsiY29tcGFueV9pZCI6MX19.H47V3kTUztWdw-wWQM4L36aGr3wHtC3BtpwaWgTc-ZA