# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::V1::CompanyUserInvitationsMailer`.
# Please instead update this file by running `bin/tapioca dsl Api::V1::CompanyUserInvitationsMailer`.

class Api::V1::CompanyUserInvitationsMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def invite_user; end
  end
end
