# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::V1::UsersMailer`.
# Please instead update this file by running `bin/tapioca dsl Api::V1::UsersMailer`.

class Api::V1::UsersMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def signup; end
  end
end
